# Generated by Django 3.0.7 on 2020-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20200702_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contributor',
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.CharField(default='User', max_length=200),
        ),
    ]
